FROM oraclelinux:7-slim
COPY ./tmp/oracle-graph-20.1.0.x86_64.rpm /tmp
RUN rpm -ivh /tmp/oracle-graph-20.1.0.x86_64.rpm \
 && rm /tmp/oracle-graph-20.1.0.x86_64.rpm \
 && yum install -y java-1.8.0-openjdk-devel expect \
 && yum clean all \
 && rm -rf /var/cache/yum/*
EXPOSE 7007
ENV PATH=$PATH:/opt/oracle/graph/pgx/bin
WORKDIR /opt/oracle/graph/pgx/bin
CMD ["sh", "start-server"]
