
-- Generated by ORDS REST Data Services 19.3.0.r3191521
-- Schema: DEMO_USER  Date: Wed Feb 26 06:16:58 2020 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEVELOPER',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'DEVELOPER',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'warehouseAPI',
      p_base_path      => '/salesAPI/',
      p_items_per_page => 100,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'stores',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'stores',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select * from OOW_DEMO_STORES');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'store/popular',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'store/popular',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select OOW_DEMO_STORES.STORE_ADDRESS, TO_CHAR(sum(HIST.QUANTITY*HIST.ITEM_PRICE),''$9,999,999'') as SALES
from OOW_DEMO_STORES, OOW_DEMO_SALES_HISTORY HIST
where HIST.STORE_ID=OOW_DEMO_STORES.ID
group by OOW_DEMO_STORES.STORE_ADDRESS
order by SALES desc');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'product/inventoryForecastingAPI/{store_add}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'product/inventoryForecastingAPI/{store_add}',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select OOW_DEMO_STORES.STORE_ADDRESS,PRODUCTS.ID as PRODUCT_ID,PRODUCTS.ITEM_NAME,PRODUCTS.TYPE as ITEM_TYPE,TO_CHAR(PRODUCTS.MSRP, ''$9,999.00'') AS Unitprice , CAST(SUM(PREDICTED_SOLD_COUNT) AS INT) TOTAL_PRED, CAST((SUM(PREDICTED_SOLD_COUNT)/5) as INT) CURRENTLY_AVAILABLE, CAST((SUM(PREDICTED_SOLD_COUNT) - (SUM(PREDICTED_SOLD_COUNT)/5)) as INT) TO_BE_ORDERD, ''N'' RISK_ITEMS
from OOW_DEMO_ITEMS PRODUCTS, ITEM_SOLD_PREDICTION, OOW_DEMO_STORES
where PRODUCTS.ID=ITEM_SOLD_PREDICTION.PRODUCT_ID and OOW_DEMO_STORES.ID=ITEM_SOLD_PREDICTION.STORE_ID and OOW_DEMO_STORES.STORE_ADDRESS IN (:store_add)
group by PRODUCTS.ID,PRODUCTS.ITEM_NAME,PRODUCTS.TYPE,PRODUCTS.MSRP,OOW_DEMO_STORES.STORE_ADDRESS
order by TO_BE_ORDERD desc');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'product/trendingProductAPI/{store_add}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'warehouseAPI',
      p_pattern        => 'product/trendingProductAPI/{store_add}',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select OOW_DEMO_ITEMS.ITEM_NAME, sum(HIST.QUANTITY) as HIGHEST_SELL
from OOW_DEMO_SALES_HISTORY HIST, OOW_DEMO_ITEMS, OOW_DEMO_STORES
where OOW_DEMO_ITEMS.ID= HIST.PRODUCT_ID and OOW_DEMO_STORES.ID=HIST.STORE_ID and OOW_DEMO_STORES.STORE_ADDRESS IN (:store_add)
group by OOW_DEMO_ITEMS.ITEM_NAME
order by sum(HIST.QUANTITY) desc');

        
COMMIT;

END;